version: 3.3

services:
  app:
    build: ./code/web
    image: scisynergy:latest
    ports:
      - 80:8080
    environment:
      - NEO4J_URI=bolt://datagraph:7687
    networks:
      - scisynergynet
    links:
      - db
  db:
    image: neo4j:3.3.3
    container_name: graph_db
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "none"
    networks:
      scisynergynet:
        aliases:
          - "datagraph"
    volumes:
      - ./data:/data
networks:
  scisynergynet:
    driver: bridge